BF: delay calling any function which might raise an Exception
exception might be defined (now) above in the same file.
Without this it was causing me

(Pdb) p requests_document_loader()
*** ImportError: ImportError('cannot import name JsonLdError',)